### ISSUE TITLE
useUrlHash issue with jQuery selector

### ISSUE THREAD

**Issue by b-e** [techlab/SmartWizard#14]
Hey guys,
awesome project. 
When I integrated it in a website, I did find an issue. With the useURLhash and backButtonSupport set to true, I was getting this error:
`Uncaught Error: Syntax error, unrecognized expression: a[href*=#step-personal-data]`
triggered by Sizzle. I'm using jQuery 2.x and SmartWizard 4.0.5

Turned out that the issue is related to 2 very similar lines of code in SmartWizard:
`var elm = $("a[href*="+hash+"]");` and
`var elm = $("a[href*="+window.location.hash+"]");`

I got it working by encapsulating the hash string into quotes, as per jQuery syntax:
`var elm = $("a[href*='"+hash+"']");` 

I forked the repo here [https://github.com/b-e/SmartWizard/blob/master/js/jquery.smartWizard.js](url), and can open a PR

**Comment by techlab** [comment]
Thank you so much for reporting the issue and the fixes. 👍

**Comment by techlab** [comment]
Your fix is applied on **SmartWizard v4.1.1**
And it is now compatible with jQuery 1.9+, jQuery 2+ and jQuery 3+
Thank you for your help
