### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: a[href*=#step-x]

### ISSUE THREAD

**Issue by backids99** [techlab/SmartWizard#15]
for each request by #step-x address will appear on the console error: Uncaught Error: Syntax error, Unrecognized expression: a[href*=#step-x]

and after I find fixes for error, I found the address https://github.com/jquery/jquery/issues/2885

to fix it, you should change `a[href*=` into `a[href*=\\`

but there is another problem, when accessing the address with #step-x will skip the previous step. 
if you do not want to step in skipped, use/change `useURLhash: false` to prevent it.

**Comment by techlab** [comment]
Thanks for reporting the issue and for recommended fix. As I understand, it is an issue with jQuery 2.x.  I will look into it.

**Comment by backids99** [comment]
thanks @techlab for improve and share awesome plugins... 👍

**Comment by techlab** [comment]
Fix is applied on **SmartWizard v4.1.1** 
And it is now compatible with latest jQuery versions (jQuery 1.9+, jQuery 2+ and jQuery 3+)
Thank you for your help
