### ISSUE TITLE
install with composer

### ISSUE THREAD

**Issue by fpolito** [techlab/SmartWizard#16]
when I install it by 
composer require techlab/smartwizard
I have the following error:

... techlab/smartwizard v4.1.2 requires jquery >=1.9.0 -> no matching package found.
Potential causes:
 A typo in the package name
 The package in not available in a stable-enough version according to your minimum-stability settings...

**Comment by techlab** [comment]
Thanks for repoting the issue, I have already fixed the issue in compisor.json file, But I may have to update the revision to reflect the change on https://packagist.org/packages/techlab/smartwizard
Will be updating the revision soon. Thanks again.

**Comment by techlab** [comment]
The istallation issue is fixed. Than you
