### ISSUE TITLE
Add extra vars into ajax post

### ISSUE THREAD

**Issue by luiseduardo** [techlab/SmartWizard#17]
I use onleavestep to send vars over step, but, is more easy if has a method to set extra vars

**Comment by techlab** [comment]
Thanks for the request, I will include in the next release

**Comment by techlab** [comment]
New option is added on `v4.1.5` as `ajaxSettings` to provid extra  settings for step content ajax calls. Thank you for the suggestion.

**Comment by leandro980** [comment]
Is there a way to change dynamically the `data` parameter of `ajaxSettings` on each/chosed step?

**Comment by vannicktrinquier** [comment]
Any update to know if it is possible to update dynamically the data paramter ?

**Comment by zieru** [comment]
Really need dynamic update the data parameter :(
