### ISSUE TITLE
Migrate from older version of Smart Wizard ?

### ISSUE THREAD

**Issue by varunmehta** [techlab/SmartWizard#22]
I'm using version 3.3.1, is there any big change to migrate from that version to 4 ? Do you have a quick checklist of add/remove stuff related to it ?

**Comment by techlab** [comment]
If you not using any customized option then it is good go, if you are using any options just check if that option exist on SmartWizard4 also. Haven't made any drastic change also on the user perspective.

And for the html, just warp all the step content divs with one div.
like 

    <div> 
        <div id="step-1" class="">
             
        </div>
        <div id="step-2" class="">
             
        </div>
        <div id="step-3" class="">
             
        </div>
    </div>

That's will be the quick list to do the migration
