### ISSUE TITLE
Reseting the wizard does not affect step state

### ISSUE THREAD

**Issue by temni** [techlab/SmartWizard#24]
If we have initiated the wizard with "hiddenSteps"/"disabledSteps" options and then call "reset" on it - the state of the nav li elements is not flushed.

**Comment by techlab** [comment]
Yes, It is the correct behavior. The initial state will be restored when we perform "reset". 
So the disabled or hidden steps remains as it is when it is reset. 
I will close this issue now and please reopen if you think still it is an issue.
Thank you
