### ISSUE TITLE
Cannot validate when inputs in col-lg-*

### ISSUE THREAD

**Issue by nobutsta** [techlab/SmartWizard#25]
I try design the form with 'col-lg-*' and put "form-group" inside. But when click next. The form just go to step 2 without validate the field. Is it normal or just a bug?

**Comment by techlab** [comment]
Please provide the HTML or add a fiddle to reproduce the issue. I don't think adding CSS class will affect the validation.

**Comment by techlab** [comment]
Closing the issue, since it couldn't be reproduced. Please reopen if you can provide an example.
