### ISSUE TITLE
[Question] Booking wizard, load available rooms after setting arrival and departure on step 1

### ISSUE THREAD

**Issue by Franklin89** [techlab/SmartWizard#26]
Hi,

Greate library...I am really enjoying how easy it is to set up the wizard in my application.

I am hoping you can give me some support for a small issue that I have. Well not really an issue, just not sure how to solve it the best way.

I hav a REST API Backend where I can get a list of rooms for a given arrival and departure date. Lets say at api.com/getrooms?arrival=...&departure=...
In the first step of my wizard I enter the arrival and departure date. That works fine. If I then switch to the second step I want to call the rest endpoint to get the list of available rooms. 

Is this possible somehow?

Thanks for the help
- Franklin

**Comment by techlab** [comment]
Please see this discussion #20, the logic is same. 
You don't have to call SmartWizard with ajax URL, instead, you can use the `leaveStep` event to take data from a step and call the ajax manually.  On ajax call back, you can call `next` method to proceed to next method.

**Comment by Franklin89** [comment]
Thanks for getting back to me and for the link to the discussion.
It gives me a good idea of how I can implement my logic. Just what I needed.
Thanks
