### ISSUE TITLE
dynamic set the elements error state

### ISSUE THREAD

**Issue by rfancn** [techlab/SmartWizard#33]
It seems there is a way to dynamically set the state for the step like:

`$('#smartwizard').smartWizard("stepState", [stepIndex], "disable");`

Except add below codes to set error state for elements, I have no idea how to achieve that target:
```
        stepState: function (stepArray, state) {
               ...
               case 'error':
                        $(selSteps).parents('li').addClass('danger');
                        break;

        }
```

Any other better suggestions?

**Comment by techlab** [comment]
Thanks for the snippet. The feature is added to the latest release [v4.3.1](https://github.com/techlab/SmartWizard/releases/tag/v4.3.1). 

**Usage:**
To add error state
```javascript
$('#smartwizard').smartWizard("stepState", [2], "error-on");
```
To remove error state
```javascript
$('#smartwizard').smartWizard("stepState", [2], "error-off");
```
