### ISSUE TITLE
Validator problem

### ISSUE THREAD

**Issue by g14nluk4** [techlab/SmartWizard#36]
hi everyone , when i try to validate 2 inputs in 1 step it just validate 1 of them (randomly) , do you know why?  i alredy saw the documentation, but there is nothing about 2 inputs in 1 step and i think no1 calculated that (validate 2 inputs in 1 step)

`<div id="form-step-1" role="form" data-toggle="validator">
               <div class="form-group">
                                    <label for="name">Name:</label>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Write your  name" required>
                                    <div class="help-block with-errors"></div>
                                    <label for="surname">Surname:</label>
                                    <input type="text" class="form-control" name="surname" id="surname" placeholder="Write your surname" required>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>`

**Comment by xihad76** [comment]
Your html looks alright to me. and multiple inputs should not be a problem for validating all of them. May be the problem lies in your JavaScript implementation of the validator.

**Comment by g14nluk4** [comment]
hey thanks for your answer ,  this is my javascript function with validate: `$("#smartwizard").on("leaveStep", function (e, anchorObject, stepNumber, stepDirection) {
                    var elmForm = $("#form-step-" + stepNumber);
                    if (stepNumber == 2) {
                       
                    }
                    if (stepNumber == 1 && stepDirection == 'forward') {
                        if (!confirm("If you press ok , timer will start and you couldn't go back until you finish this survey")) {
                            return false;
                        } else {
                            n = 1;
                            input = 0;
                            var d = new Date();
                            start = d.getTime();
                            return true;
                        }
                    }
                    if (stepNumber == 2 && stepDirection == 'backward') {
                        alert('You have to finish this survey');
                        return false;
                    }
            <%--      if (stepNumber > 1) {
                        alert(<%=last%>);
                        if (send("quante cose?") == false) {
                            return false;
                        }
                        if (send("quante cose?") == true) {
                            return true;
                        }
                    } --%>
                    // stepDirection === 'forward' :- this condition allows to do the form validation 
                    // only on forward navigation, that makes easy navigation on backwards still do the validation when going next

                    if (stepDirection === 'forward' && elmForm) {
                        elmForm.validator('validate');
                        var elmErr = elmForm.children('.has-error');
                        if (elmErr && elmErr.length > 0) {

                            // Form validation failed
                            return false;
                        }
                        if ($("#Password").val() != str) {

                            alert("  Wrong Password");
                            return false;
                        }

                        if (stepNumber > 0) {

                            if ($("#name").val().length < 1) {
                                alert("Insert your name");
                                return false
                            }
                            if ($("#surname").val().length < 1) {
                                alert("Insert your surname");
                                return false
                            }
                        }


                    }
                    return true;
                });`

**Comment by techlab** [comment]
Adding multiple input doesn't raise any problem usually. Please add an example on https://jsfiddle.net if you still have the issue. Closing the issue, for now, reopen if required.

**Comment by iryanjan18** [comment]
I think this doesn't work with multiple rows
