### ISSUE TITLE
Not compatible with jQuery 3.2.1

### ISSUE THREAD

**Issue by BobWalsh** [techlab/SmartWizard#38]
`jquery-3.2.1.slim.min.js:2 jQuery.Deferred exception: this.pages.finish is not a function TypeError: this.pages.finish is not a function
    at SmartWizard._transitPage (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:414:24)
    at SmartWizard._loadStepContent (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:388:22)
    at SmartWizard._showStep (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:338:18)
    at SmartWizard.init (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:105:18)
    at new SmartWizard (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:72:14)
    at HTMLDivElement.<anonymous> (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:604:49)
    at Function.each (https://code.jquery.com/jquery-3.2.1.slim.min.js:2:2919)
    at r.fn.init.each (https://code.jquery.com/jquery-3.2.1.slim.min.js:2:1207)
    at r.fn.init.$.fn.smartWizard (file:///Users/bobwalsh/twee-fi/js/jquery.smartWizard.js:602:25)
    at HTMLDocument.<anonymous> (file:///Users/bobwalsh/twee-fi/js/twee-fi.js:2:21) undefined
`
and then this error:
jquery-3.2.1.slim.min.js:2 Uncaught TypeError: this.pages.finish is not a function
    at SmartWizard._transitPage (jquery.smartWizard.js:414)
    at SmartWizard._loadStepContent (jquery.smartWizard.js:388)
    at SmartWizard._showStep (jquery.smartWizard.js:338)
    at SmartWizard.init (jquery.smartWizard.js:105)
    at new SmartWizard (jquery.smartWizard.js:72)
    at HTMLDivElement.<anonymous> (jquery.smartWizard.js:604)
    at Function.each (jquery-3.2.1.slim.min.js:2)
    at r.fn.init.each (jquery-3.2.1.slim.min.js:2)
    at r.fn.init.$.fn.smartWizard (jquery.smartWizard.js:602)
    at HTMLDocument.<anonymous> (twee-fi.js:2)

**Comment by techlab** [comment]
Please use jQuery full versions (`jquery-3.3.x.min.js`) as the jQuery slim version (`jquery-3.3.x.slim.min.js`) is not yet supported.

**Comment by Rajendra5oni** [comment]
@ [techlab](https://github.com/techlab)
[Dipu Raj](https://github.com/techlab)

Hi... Dipu Raj Sir 
I have used jQuery Smart Wizard v6 plugin with Bootstrap v5.1.3 in my c# web Application but somehow it is not working. i have attached the output screen and  .aspx code in this post. please check it and help me sir... there is no one error on run of this page.

**### smartWizard is not working
![smartwizard demo screen](https://user-images.githubusercontent.com/116986673/198859062-00b0e258-3e63-4954-8cd2-55b99bc54656.jpeg)
.**

`<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="Server">
    
    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <link href="../Content/smart_wizard.min.css" rel="stylesheet" />

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <div class="container">
                <%--<form action="#" id="loanprocess">--%>
                <br />
                <div class="row">
                    <section id="loanaccountform">
                        <div class="form-horizontal">
                            <h4 style="font-weight: bold">Loan Process</h4>
                            <hr />
                            <asp:PlaceHolder runat="server" ID="ErrorMessage" Visible="false">
                                <p class="text-danger">
                                    <asp:Literal runat="server" ID="FailureText" />
                                </p>
                            </asp:PlaceHolder>
                        </div>
                    </section>
                </div>
                <div id="smartwizard">
                    <ul>
                        <li>
                            <a href="#step1">Adhar<br />
                                <small>Verification</small>
                            </a>
                        </li>
                        <li>
                            <a href="#step2">PAN<br />
                                <small>Verification</small>
                            </a>
                        </li>
                        <li>
                            <a href="#step3">Bank<br />
                                <small>Verification</small>
                            </a>
                        </li>
                        <li>
                            <a href="#step4">Address<br />
                                <small>Verification</small>
                            </a>
                        </li>
                        <li>
                            <a href="#step5">Employment<br />
                                <small>Verification</small>
                            </a>
                        </li>
                        <li>
                            <a href="#step6">Mortgage<br />
                                <small>Process</small>
                            </a>
                        </li>
                    </ul>
                </div>
                <%--</form>--%>
            </div>
        </ContentTemplate>
    </asp:UpdatePanel>

    <script type="text/javascript" src="../Scripts/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="../Scripts/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="../Scripts/bootstrap.min.js"></script>

    <script type="text/javascript" src="../Scripts/jquery.smartWizard.min.js"></script>

    <script type="text/javascript">
        // SmartWizard initialize
        $('.smartwizard').smartWizard();
    </script>

</asp:Content>`

**Comment by techlab** [comment]
@Rajendra5oni 
Since the CSS class is not defined to any element, you should select the element with `id` not `class`. This is not an issue with the plugin but your code. Please correct with the following change.
```js
$('#smartwizard').smartWizard();
```

**Comment by Rajendra5oni** [comment]
> 

thank you sir for your valuable reply.
Sorry sir... i don't want to say that an issue with the plugin but their is some mistake in my code but i could not find it.
i have tried also $('#smartwizard').smartWizard(); but still it is not working.
