### ISSUE TITLE
smartWizard goToStep method not work

### ISSUE THREAD

**Issue by nakry224** [techlab/SmartWizard#39]
Hi,
I have 4 steps and I just want to jump a step with goToStep function in the leaveStep event - however, I would like to decide which step I want to move to with the 'Next' button in built in smart wizard, based on what the user selects in the first step i.e. if some value is selected in Step 1, then on clicking next, I can check for the value and then move to Step X or Y etc...
Is this possible? Can I get an example?

here my code
`
$("#myWizard").on("leaveStep",` function (e, anchorObject, stepNumber, stepDirection) {
                if (stepDirection === "forward"){ 
                    var isStepValid= self.validateSteps(stepNumber); //my step validation function, return true or false
                    if(stepNumber == 0 && userSelected == someValue){
                        console.log("................. gotostep 3 => Skip step 2"); 
                        $('#myWizard').smartWizard("goToStep",3);   //this do nothing, the goToStep doesn't  work, the logic next step is load (the step 2 until the step 3)                    
                    }else{
                        return isStepValid;
                    }
                }
            });
`
where's my mistake?
thanks for help!

**Comment by eliteproxy7** [comment]
anyone figure this out yet?

**Comment by techlab** [comment]
`goToStep` option is removed on the latest versions since. There is not an alternative option provided yet. Feel free to re-open the issue or add a new issue to the request for the option. Thanks

**Comment by seanmavley** [comment]
Adding this: 
```
    goToStep: function (stepNum) {
      this._showStep(stepNum);
    },
```
anywhere in here: https://github.com/techlab/SmartWizard/blob/master/dist/js/jquery.smartWizard.js#L552-L620

Then calling it like so:
`$('#smartwizard').smartWizard('goToStep', value);` 

does the trick.

**Comment by manumuve** [comment]
What's the reason to have this function disabled by default?

**Comment by buttflattery** [comment]
@manumuve i think the reason behind removing it would be that it does not respect the options if selected not to navigate away from the step using `enableAllSteps:false` it would still allow the user to move to the next steps by just calling the method in console, maybe maybe not. just a wild guess.

**Comment by phivh** [comment]
goToStep in my solution - based on index has been assign: 
```
var idx = 2; // example if you want use a button or <a> tag to navigate exact step, you can assign an attribute as data-index="2"
$(obj).find('li').eq(idx).children('a').trigger('click');
```
$(obj): mean navs list
