### ISSUE TITLE
TypeError: elmForm.validator is not a function

### ISSUE THREAD

**Issue by djary** [techlab/SmartWizard#42]
hi , i want Implementation InputValidation Example 
`          $("#smartwizard").on("leaveStep", function(e, anchorObject, stepNumber, stepDirection) {
                var elmForm = $("#form-step-" + stepNumber);
                // stepDirection === 'forward' :- this condition allows to do the form validation 
                // only on forward navigation, that makes easy navigation on backwards still do the validation when going next
                if(stepDirection === 'forward' && elmForm){
                    elmForm.validator('validate'); 
                    var elmErr = elmForm.children('.has-error');
                    if(elmErr && elmErr.length > 0){
                        // Form validation failed
                        return false;    
                    }
                }
                return true;
            });`
but get me an error

> elmForm.validator is not a function

and not work anybody have example for asp.net mvc 5 ?

**Comment by techlab** [comment]
You have to include jQuery Validator plugin as shown in the [example](https://github.com/techlab/SmartWizard/blob/master/examples/smartwizard-input.html#L90l).
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
```
