### ISSUE TITLE
Key navigation with SmartWizard on a modal

### ISSUE THREAD

**Issue by andliz** [techlab/SmartWizard#43]
I'm having a problem with key navigation (left, right keys) when I place a SmartWizard on a bootstrap modal.  Every key hit brings me 2 tabs forward or backward. Buttons Next and Prev work completely fine though.

**Comment by techlab** [comment]
Cannot reproduce the issue. Please see the modal implementation on [https://github.com/techlab/SmartWizard/blob/master/examples/smartwizard-modal.html](https://github.com/techlab/SmartWizard/blob/master/examples/smartwizard-modal.html). Thanks.
