### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by bryanrscott** [techlab/SmartWizard#44]
Hi
Just wondering if bootstrap 4 support is planned
cheers

**Comment by suprahh** [comment]
@bryanrscott did you find some wizard for bootstrap 4???

**Comment by bryanrscott** [comment]
Not yet.  Got as far as adding this
    <style>
        .sw-theme-arrows > ul.step-anchor {
            display: flex;
        }
    </style>

**Comment by GedMarc** [comment]
+1 :)

**Comment by techlab** [comment]
Bootstrap 4 support is added in the latest release [v4.3.1](https://github.com/techlab/SmartWizard/releases/tag/v4.3.1). Thank you all for your support.

**Comment by GedMarc** [comment]
You da man! <3
