### ISSUE TITLE
How I could prevent scrolling when clicking Next or Previous?

### ISSUE THREAD

**Issue by mrwnmonm** [techlab/SmartWizard#61]
The demos doesn't have this behavior, but the lib does it. Whenever you click Next or Previous, the page scroll to the top of the content. How I could prevent this?  

I want it to scroll to the top of the page.

**Comment by mrwnmonm** [comment]
I figured it out. You could do it using this event:
```
$("#smartwizard").on("showStep", function(e, anchorObject, stepNumber, stepDirection) {
  window.scrollTo(0, 0);
});
```

**Comment by juliomontilla100** [comment]
Clear b.focusError() on Bootstrap.validador library
`d.prototype.validate = function() {
        var b = this;
        return a.when(this.$inputs.map(function() {
            return b.validateInput(a(this), !1)
        })).then(function() {
            b.toggleSubmit(), b.focusError()
        }), this
    `},``

**Comment by juliomontilla100** [comment]
Clear  b.focusError() function on bootstrap.validator library
![image](https://user-images.githubusercontent.com/19539130/46746298-2ea3bf00-cc85-11e8-84a4-2ed576cf6399.png)
