### ISSUE TITLE
Show Finish button in place of Next on last step

### ISSUE THREAD

**Issue by amard33p** [techlab/SmartWizard#65]
Show only Prev and Next buttons. On the final step, change Next to Finish. Basically mimic [jquery-steps](http://www.jquery-steps.com/Examples).

**Comment by cdac901** [comment]
Hi

```
$(document).ready(function() {
     $('#smartwizard').smartWizard({
       lang: {
          last: "Finish"
       }
     })

     $("#smartwizard").on("showStep", function (e, anchorObject, stepNumber, stepDirection) {
        var data = $(e.target).data('smartWizard'),
            isLastIndex = stepNumber == data.pages.length - 1

        $(e.target)
            .find('.sw-btn-next')
            .text(isLastIndex ? data.options.lang.last : data.options.lang.next)
     })
})
```

**Comment by amard33p** [comment]
> .text(isLastIndex ? data.options.lang.last : data.options.lang.next)

You are just changing the text of Next to Finish. On the last step the "Next" button becomes disabled. This is not the right way.

**Comment by amard33p** [comment]
Took some time but got it to work finally. Here's a modal example.  
https://github.com/amard33p/jq-smartwizard-modal

**Comment by weslly99** [comment]
@amard33p  the link is off

**Comment by amard33p** [comment]
> @amard33p the link is off

Yeah it was a bit buggy. I switched to https://github.com/rstaib/jquery-steps.

**Comment by snowchenlei** [comment]
> > @amard33p the link is off
> 
> Yeah it was a bit buggy. I switched to https://github.com/rstaib/jquery-steps.

example where?

**Comment by divabanana** [comment]
If anyone is still looking for a solution to this...

Give your finish button a custom class or id and an initial display state of none when you define it for example:
`<button id="finishbtn" class="btn btn-success" onclick="onFinish()"  style="display:none;">Finish</button>`

Then use the showStep event to determine if it's the final step or not. If it is, hide Next button and show Finish button, else do the opposite:
`$("#smartwizard").on("showStep", function(e, anchorObject, stepIndex, stepDirection, stepPosition) {
	if(stepPosition === 'last') {
		$(".sw-btn-next").hide();
		$("#finishbtn").show();
	} else {
		$(".sw-btn-next").show();
		$("#finishbtn").hide();
	}
});`
