### ISSUE TITLE
To add Tab Dyanmically 

### ISSUE THREAD

**Issue by velanchandru** [techlab/SmartWizard#7]
i've a requirement to add new tab's dynamically say suppose i've 5 tabs  loaded  as Wizard control and i had to add one more tab Depends on a condition on exiting from some tab(say from 3 to 4).i want added 6th tab dynamically.
Adding dynamic Tab functionality to Wizard isn't give fruit full result ,i can able to see the UI change but i'm not able to navigate through it, to my understanding since document.ready function executed so there is no chance of adding new tab functionality its not considered as wizard object, so i request you to have something like $('#wizard).reload() function feature would be great i guess.

**Comment by techlab** [comment]
Thanks for the suggestion, it will be considered on future versions of Smart Wizard 4.

**Comment by techlab** [comment]
After analizing your requirement, 
adding new steps dynamically would bring complications in to the functionality and coding.
For example, we may have to pass parameters for the step header and content for the new step etc.

So I preffered to make this functionality work in other ways with **hidden steps**.
So for example we could include a step (say 4) between steps 3 and 5 but it is completely hidden.

And when you want to show it, you can call the public method `stepState` like
     `$('#smartwizard').smartWizard("stepState", [4], "show");`

and for hidng 
     `$('#smartwizard').smartWizard("stepState", [4], "hide");`

`stepState` is also support enable, disable functionality 

Also the option parameter hiddenSteps: [] will set the steps hidden on inital load.

This feature is available form **SmartWizard v4.1.1**
Hope this will help you thank you

**Comment by Chiloh** [comment]
How can i add extra tabs because there are only four tabs by default ?

**Comment by jithjob** [comment]
I have same requirement.

**Comment by ivenms** [comment]
Same requirement for me. Depends on the selections, the total steps can be dynamic.

**Comment by pedrovieira-zz** [comment]
Same requirement here...
